local addonName, addon   = ...
addon.barNames           = { "ACTIONBUTTON", "MULTIBARBOTTOMLEFTBUTTON", "MULTIBARBOTTOMRIGHTBUTTON", "MULTIBARLEFTBUTTON", "MULTIBARRIGHTBUTTON", "MULTIBAR5BUTTON", "MULTIBAR6BUTTON", "MULTIBAR7BUTTON" }
addon.ignored            = "Ignored"
addon.isLoaded           = false
addon.settingsControls   = {}
addon.settingsIconSize   = 36
addon.unknown            = "Unknown"

addon.actionButtons      = {}

addon.actionButtons[1]   ="ACTIONBUTTON1"
addon.actionButtons[2]   ="ACTIONBUTTON2"
addon.actionButtons[3]   ="ACTIONBUTTON3"
addon.actionButtons[4]   ="ACTIONBUTTON4"
addon.actionButtons[5]   ="ACTIONBUTTON5"
addon.actionButtons[6]   ="ACTIONBUTTON6"
addon.actionButtons[7]   ="ACTIONBUTTON7"
addon.actionButtons[8]   ="ACTIONBUTTON8"
addon.actionButtons[9]   ="ACTIONBUTTON9"
addon.actionButtons[10]  ="ACTIONBUTTON10"
addon.actionButtons[11]  ="ACTIONBUTTON11"
addon.actionButtons[12]  ="ACTIONBUTTON12"

addon.actionButtons[13]  ="ACTIONBUTTON1"
addon.actionButtons[14]  ="ACTIONBUTTON2"
addon.actionButtons[15]  ="ACTIONBUTTON3"
addon.actionButtons[16]  ="ACTIONBUTTON4"
addon.actionButtons[17]  ="ACTIONBUTTON5"
addon.actionButtons[18]  ="ACTIONBUTTON6"
addon.actionButtons[19]  ="ACTIONBUTTON7"
addon.actionButtons[20]  ="ACTIONBUTTON8"
addon.actionButtons[21]  ="ACTIONBUTTON9"
addon.actionButtons[22]  ="ACTIONBUTTON10"
addon.actionButtons[23]  ="ACTIONBUTTON11"
addon.actionButtons[24]  ="ACTIONBUTTON12"

addon.actionButtons[25]  = "MULTIBARRIGHTBUTTON1"
addon.actionButtons[26]  = "MULTIBARRIGHTBUTTON2"
addon.actionButtons[27]  = "MULTIBARRIGHTBUTTON3"
addon.actionButtons[28]  = "MULTIBARRIGHTBUTTON4"
addon.actionButtons[29]  = "MULTIBARRIGHTBUTTON5"
addon.actionButtons[30]  = "MULTIBARRIGHTBUTTON6"
addon.actionButtons[31]  = "MULTIBARRIGHTBUTTON7"
addon.actionButtons[32]  = "MULTIBARRIGHTBUTTON8"
addon.actionButtons[33]  = "MULTIBARRIGHTBUTTON9"
addon.actionButtons[34]  = "MULTIBARRIGHTBUTTON10"
addon.actionButtons[35]  = "MULTIBARRIGHTBUTTON11"
addon.actionButtons[36]  = "MULTIBARRIGHTBUTTON12"

addon.actionButtons[37]  = "MULTIBARLEFTBUTTON1"
addon.actionButtons[38]  = "MULTIBARLEFTBUTTON2"
addon.actionButtons[39]  = "MULTIBARLEFTBUTTON3"
addon.actionButtons[40]  = "MULTIBARLEFTBUTTON4"
addon.actionButtons[41]  = "MULTIBARLEFTBUTTON5"
addon.actionButtons[42]  = "MULTIBARLEFTBUTTON6"
addon.actionButtons[43]  = "MULTIBARLEFTBUTTON7"
addon.actionButtons[44]  = "MULTIBARLEFTBUTTON8"
addon.actionButtons[45]  = "MULTIBARLEFTBUTTON9"
addon.actionButtons[46]  = "MULTIBARLEFTBUTTON10"
addon.actionButtons[47]  = "MULTIBARLEFTBUTTON11"
addon.actionButtons[48]  = "MULTIBARLEFTBUTTON12"

addon.actionButtons[49]  = "MULTIBARBOTTOMRIGHTBUTTON1"
addon.actionButtons[50]  = "MULTIBARBOTTOMRIGHTBUTTON2"
addon.actionButtons[51]  = "MULTIBARBOTTOMRIGHTBUTTON3"
addon.actionButtons[52]  = "MULTIBARBOTTOMRIGHTBUTTON4"
addon.actionButtons[53]  = "MULTIBARBOTTOMRIGHTBUTTON5"
addon.actionButtons[54]  = "MULTIBARBOTTOMRIGHTBUTTON6"
addon.actionButtons[55]  = "MULTIBARBOTTOMRIGHTBUTTON7"
addon.actionButtons[56]  = "MULTIBARBOTTOMRIGHTBUTTON8"
addon.actionButtons[57]  = "MULTIBARBOTTOMRIGHTBUTTON9"
addon.actionButtons[58]  = "MULTIBARBOTTOMRIGHTBUTTON10"
addon.actionButtons[59]  = "MULTIBARBOTTOMRIGHTBUTTON11"
addon.actionButtons[60]  = "MULTIBARBOTTOMRIGHTBUTTON12"

addon.actionButtons[61]  = "MULTIBARBOTTOMLEFTBUTTON1"
addon.actionButtons[62]  = "MULTIBARBOTTOMLEFTBUTTON2"
addon.actionButtons[63]  = "MULTIBARBOTTOMLEFTBUTTON3"
addon.actionButtons[64]  = "MULTIBARBOTTOMLEFTBUTTON4"
addon.actionButtons[65]  = "MULTIBARBOTTOMLEFTBUTTON5"
addon.actionButtons[66]  = "MULTIBARBOTTOMLEFTBUTTON6"
addon.actionButtons[67]  = "MULTIBARBOTTOMLEFTBUTTON7"
addon.actionButtons[68]  = "MULTIBARBOTTOMLEFTBUTTON8"
addon.actionButtons[69]  = "MULTIBARBOTTOMLEFTBUTTON9"
addon.actionButtons[70]  = "MULTIBARBOTTOMLEFTBUTTON10"
addon.actionButtons[71]  = "MULTIBARBOTTOMLEFTBUTTON11"
addon.actionButtons[72]  = "MULTIBARBOTTOMLEFTBUTTON12"

-- Target Possessed
addon.actionButtons[121] ="ACTIONBUTTON1"
addon.actionButtons[122] ="ACTIONBUTTON2"
addon.actionButtons[123] ="ACTIONBUTTON3"
addon.actionButtons[124] ="ACTIONBUTTON4"
addon.actionButtons[125] ="ACTIONBUTTON5"
addon.actionButtons[126] ="ACTIONBUTTON6"
addon.actionButtons[127] ="ACTIONBUTTON7"
addon.actionButtons[128] ="ACTIONBUTTON8"
addon.actionButtons[129] ="ACTIONBUTTON9"
addon.actionButtons[130] ="ACTIONBUTTON10"
addon.actionButtons[131] ="ACTIONBUTTON11"
addon.actionButtons[132] ="ACTIONBUTTON12"

addon.actionButtons[145] = "MULTIBAR5BUTTON1"
addon.actionButtons[146] = "MULTIBAR5BUTTON2"
addon.actionButtons[147] = "MULTIBAR5BUTTON3"
addon.actionButtons[148] = "MULTIBAR5BUTTON4"
addon.actionButtons[149] = "MULTIBAR5BUTTON5"
addon.actionButtons[150] = "MULTIBAR5BUTTON6"
addon.actionButtons[151] = "MULTIBAR5BUTTON7"
addon.actionButtons[152] = "MULTIBAR5BUTTON8"
addon.actionButtons[153] = "MULTIBAR5BUTTON9"
addon.actionButtons[154] = "MULTIBAR5BUTTON10"
addon.actionButtons[155] = "MULTIBAR5BUTTON11"
addon.actionButtons[156] = "MULTIBAR5BUTTON12"

addon.actionButtons[157] = "MULTIBAR6BUTTON1"
addon.actionButtons[158] = "MULTIBAR6BUTTON2"
addon.actionButtons[159] = "MULTIBAR6BUTTON3"
addon.actionButtons[160] = "MULTIBAR6BUTTON4"
addon.actionButtons[161] = "MULTIBAR6BUTTON5"
addon.actionButtons[162] = "MULTIBAR6BUTTON6"
addon.actionButtons[163] = "MULTIBAR6BUTTON7"
addon.actionButtons[164] = "MULTIBAR6BUTTON8"
addon.actionButtons[165] = "MULTIBAR6BUTTON9"
addon.actionButtons[166] = "MULTIBAR6BUTTON10"
addon.actionButtons[167] = "MULTIBAR6BUTTON11"
addon.actionButtons[168] = "MULTIBAR6BUTTON12"

addon.actionButtons[169] = "MULTIBAR7BUTTON1"
addon.actionButtons[170] = "MULTIBAR7BUTTON2"
addon.actionButtons[171] = "MULTIBAR7BUTTON3"
addon.actionButtons[172] = "MULTIBAR7BUTTON4"
addon.actionButtons[173] = "MULTIBAR7BUTTON5"
addon.actionButtons[174] = "MULTIBAR7BUTTON6"
addon.actionButtons[175] = "MULTIBAR7BUTTON7"
addon.actionButtons[176] = "MULTIBAR7BUTTON8"
addon.actionButtons[177] = "MULTIBAR7BUTTON9"
addon.actionButtons[178] = "MULTIBAR7BUTTON10"
addon.actionButtons[179] = "MULTIBAR7BUTTON11"
addon.actionButtons[180] = "MULTIBAR7BUTTON12"

-- Druid Cat Form
-- Priest Shadowform
-- Rogue Stealth
-- Warrior Battle Stance
addon.actionButtons[73]  ="ACTIONBUTTON1"
addon.actionButtons[74]  ="ACTIONBUTTON2"
addon.actionButtons[75]  ="ACTIONBUTTON3"
addon.actionButtons[76]  ="ACTIONBUTTON4"
addon.actionButtons[77]  ="ACTIONBUTTON5"
addon.actionButtons[78]  ="ACTIONBUTTON6"
addon.actionButtons[79]  ="ACTIONBUTTON7"
addon.actionButtons[80]  ="ACTIONBUTTON8"
addon.actionButtons[81]  ="ACTIONBUTTON9"
addon.actionButtons[82]  ="ACTIONBUTTON10"
addon.actionButtons[83]  ="ACTIONBUTTON11"
addon.actionButtons[84]  ="ACTIONBUTTON12"
-- Druid Prowl
-- Rogue Shadow Dance
-- Warrior Defensive Stance
addon.actionButtons[85]  ="ACTIONBUTTON1"
addon.actionButtons[86]  ="ACTIONBUTTON2"
addon.actionButtons[87]  ="ACTIONBUTTON3"
addon.actionButtons[88]  ="ACTIONBUTTON4"
addon.actionButtons[89]  ="ACTIONBUTTON5"
addon.actionButtons[90]  ="ACTIONBUTTON6"
addon.actionButtons[91]  ="ACTIONBUTTON7"
addon.actionButtons[92]  ="ACTIONBUTTON8"
addon.actionButtons[93]  ="ACTIONBUTTON9"
addon.actionButtons[94]  ="ACTIONBUTTON10"
addon.actionButtons[95]  ="ACTIONBUTTON11"
addon.actionButtons[96]  ="ACTIONBUTTON12"
-- Druid Bear Form, Warrior Berserker Stance
addon.actionButtons[97]  ="ACTIONBUTTON1"
addon.actionButtons[98]  ="ACTIONBUTTON2"
addon.actionButtons[99]  ="ACTIONBUTTON3"
addon.actionButtons[100] ="ACTIONBUTTON4"
addon.actionButtons[101] ="ACTIONBUTTON5"
addon.actionButtons[102] ="ACTIONBUTTON6"
addon.actionButtons[103] ="ACTIONBUTTON7"
addon.actionButtons[104] ="ACTIONBUTTON8"
addon.actionButtons[105] ="ACTIONBUTTON9"
addon.actionButtons[106] ="ACTIONBUTTON10"
addon.actionButtons[107] ="ACTIONBUTTON11"
addon.actionButtons[108] ="ACTIONBUTTON12"
-- Druid Moonkin Form
addon.actionButtons[109] ="ACTIONBUTTON1"
addon.actionButtons[110] ="ACTIONBUTTON2"
addon.actionButtons[111] ="ACTIONBUTTON3"
addon.actionButtons[112] ="ACTIONBUTTON4"
addon.actionButtons[113] ="ACTIONBUTTON5"
addon.actionButtons[114] ="ACTIONBUTTON6"
addon.actionButtons[115] ="ACTIONBUTTON7"
addon.actionButtons[116] ="ACTIONBUTTON8"
addon.actionButtons[117] ="ACTIONBUTTON9"
addon.actionButtons[118] ="ACTIONBUTTON10"
addon.actionButtons[119] ="ACTIONBUTTON11"
addon.actionButtons[120] ="ACTIONBUTTON12"

-- Unknown
addon.actionButtons[133] = ""
addon.actionButtons[134] = ""
addon.actionButtons[135] = ""
addon.actionButtons[136] = ""
addon.actionButtons[137] = ""
addon.actionButtons[138] = ""
addon.actionButtons[139] = ""
addon.actionButtons[140] = ""
addon.actionButtons[141] = ""
addon.actionButtons[142] = ""
addon.actionButtons[143] = ""
addon.actionButtons[144] = ""
